### ISSUE TITLE
error: expected initializer before 'btnInterrupt'

### ISSUE THREAD

**Issue by kindzhon** [CHNleing/ESP8266_HomeKit_For_Arduino_WS2812B#1]
请教：编译出这个错是咋回事？是不是8266的核心用的不对？我用的是2.4.2
simple_led:95: error: expected initializer before 'btnInterrupt'

 void IRAM_ATTR btnInterrupt() {

**Comment by CHNleing** [comment]
btnInterrupt 没有初始化
